//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка.
    /// </summary>
    // *** Start programmer edit section *** (Application CustomAttributes)

    // *** End programmer edit section *** (Application CustomAttributes)
    [AutoAltered()]
    [Caption("Заявка")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ApplicationE", new string[] {
            "ApplicationDate as \'Дата заявки\'",
            "Speaker as \'Спикер\'",
            "Speaker.Surname as \'\'",
            "Speaker.Name as \'\'",
            "Speaker.Patronymic as \'\'",
            "Book as \'Название книги\'",
            "Book.Name as \'\'"}, Hidden=new string[] {
            "Speaker.Surname",
            "Speaker.Name",
            "Book.Name"})]
    [MasterViewDefineAttribute("ApplicationE", "Book", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ApplicationL", new string[] {
            "ApplicationDate as \'Дата заявки\'",
            "Speaker.Surname as \'Спикер\'",
            "Book.Name as \'Название книги\'"})]
    public class Application : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fApplicationDate;
        
        private IIS.BookDemo.Book fBook;
        
        private IIS.BookDemo.Speaker fSpeaker;
        
        // *** Start programmer edit section *** (Application CustomMembers)

        // *** End programmer edit section *** (Application CustomMembers)

        
        /// <summary>
        /// ApplicationDate.
        /// </summary>
        // *** Start programmer edit section *** (Application.ApplicationDate CustomAttributes)

        // *** End programmer edit section *** (Application.ApplicationDate CustomAttributes)
        public virtual System.DateTime ApplicationDate
        {
            get
            {
                // *** Start programmer edit section *** (Application.ApplicationDate Get start)

                // *** End programmer edit section *** (Application.ApplicationDate Get start)
                System.DateTime result = this.fApplicationDate;
                // *** Start programmer edit section *** (Application.ApplicationDate Get end)

                // *** End programmer edit section *** (Application.ApplicationDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Application.ApplicationDate Set start)

                // *** End programmer edit section *** (Application.ApplicationDate Set start)
                this.fApplicationDate = value;
                // *** Start programmer edit section *** (Application.ApplicationDate Set end)

                // *** End programmer edit section *** (Application.ApplicationDate Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Application.Book CustomAttributes)

        // *** End programmer edit section *** (Application.Book CustomAttributes)
        [PropertyStorage(new string[] {
                "Книга"})]
        [NotNull()]
        public virtual IIS.BookDemo.Book Book
        {
            get
            {
                // *** Start programmer edit section *** (Application.Book Get start)

                // *** End programmer edit section *** (Application.Book Get start)
                IIS.BookDemo.Book result = this.fBook;
                // *** Start programmer edit section *** (Application.Book Get end)

                // *** End programmer edit section *** (Application.Book Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Application.Book Set start)

                // *** End programmer edit section *** (Application.Book Set start)
                this.fBook = value;
                // *** Start programmer edit section *** (Application.Book Set end)

                // *** End programmer edit section *** (Application.Book Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Application.Speaker CustomAttributes)

        // *** End programmer edit section *** (Application.Speaker CustomAttributes)
        [PropertyStorage(new string[] {
                "Спикер"})]
        [NotNull()]
        public virtual IIS.BookDemo.Speaker Speaker
        {
            get
            {
                // *** Start programmer edit section *** (Application.Speaker Get start)

                // *** End programmer edit section *** (Application.Speaker Get start)
                IIS.BookDemo.Speaker result = this.fSpeaker;
                // *** Start programmer edit section *** (Application.Speaker Get end)

                // *** End programmer edit section *** (Application.Speaker Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Application.Speaker Set start)

                // *** End programmer edit section *** (Application.Speaker Set start)
                this.fSpeaker = value;
                // *** Start programmer edit section *** (Application.Speaker Set end)

                // *** End programmer edit section *** (Application.Speaker Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ApplicationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationE", typeof(IIS.BookDemo.Application));
                }
            }
            
            /// <summary>
            /// "ApplicationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationL", typeof(IIS.BookDemo.Application));
                }
            }
        }
    }
}
