//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// План встречи.
    /// </summary>
    // *** Start programmer edit section *** (MeetingPlan CustomAttributes)

    // *** End programmer edit section *** (MeetingPlan CustomAttributes)
    [AutoAltered()]
    [Caption("План встречи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MeetingPlanE", new string[] {
            "MeetingDate as \'Дата встречи\'"})]
    [View("MeetingPlanL", new string[] {
            "MeetingDate as \'Дата встречи\'"})]
    public class MeetingPlan : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fMeetingDate;
        
        // *** Start programmer edit section *** (MeetingPlan CustomMembers)

        // *** End programmer edit section *** (MeetingPlan CustomMembers)

        
        /// <summary>
        /// MeetingDate.
        /// </summary>
        // *** Start programmer edit section *** (MeetingPlan.MeetingDate CustomAttributes)

        // *** End programmer edit section *** (MeetingPlan.MeetingDate CustomAttributes)
        public virtual System.DateTime MeetingDate
        {
            get
            {
                // *** Start programmer edit section *** (MeetingPlan.MeetingDate Get start)

                // *** End programmer edit section *** (MeetingPlan.MeetingDate Get start)
                System.DateTime result = this.fMeetingDate;
                // *** Start programmer edit section *** (MeetingPlan.MeetingDate Get end)

                // *** End programmer edit section *** (MeetingPlan.MeetingDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MeetingPlan.MeetingDate Set start)

                // *** End programmer edit section *** (MeetingPlan.MeetingDate Set start)
                this.fMeetingDate = value;
                // *** Start programmer edit section *** (MeetingPlan.MeetingDate Set end)

                // *** End programmer edit section *** (MeetingPlan.MeetingDate Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MeetingPlanE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingPlanE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingPlanE", typeof(IIS.BookDemo.MeetingPlan));
                }
            }
            
            /// <summary>
            /// "MeetingPlanL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingPlanL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingPlanL", typeof(IIS.BookDemo.MeetingPlan));
                }
            }
        }
    }
}
