//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.bookDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спикер.
    /// </summary>
    // *** Start programmer edit section *** (Speaker CustomAttributes)

    // *** End programmer edit section *** (Speaker CustomAttributes)
    [AutoAltered()]
    [Caption("Спикер")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SpeakerE", new string[] {
            "Surname as \'Фамилия\'",
            "Name as \'Имя\'",
            "Patronymic as \'Отчество\'"})]
    [View("SpeakerL", new string[] {
            "Surname as \'Фамилия\'",
            "Name as \'Имя\'",
            "Patronymic as \'Отчество\'"})]
    public class Speaker : ICSSoft.STORMNET.DataObject
    {
        
        private string fSurname;
        
        private string fName;
        
        private string fPatronymic;
        
        // *** Start programmer edit section *** (Speaker CustomMembers)

        // *** End programmer edit section *** (Speaker CustomMembers)

        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Speaker.Surname CustomAttributes)

        // *** End programmer edit section *** (Speaker.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.Surname Get start)

                // *** End programmer edit section *** (Speaker.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Speaker.Surname Get end)

                // *** End programmer edit section *** (Speaker.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.Surname Set start)

                // *** End programmer edit section *** (Speaker.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Speaker.Surname Set end)

                // *** End programmer edit section *** (Speaker.Surname Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Speaker.Name CustomAttributes)

        // *** End programmer edit section *** (Speaker.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.Name Get start)

                // *** End programmer edit section *** (Speaker.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Speaker.Name Get end)

                // *** End programmer edit section *** (Speaker.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.Name Set start)

                // *** End programmer edit section *** (Speaker.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Speaker.Name Set end)

                // *** End programmer edit section *** (Speaker.Name Set end)
            }
        }
        
        /// <summary>
        /// Patronymic.
        /// </summary>
        // *** Start programmer edit section *** (Speaker.Patronymic CustomAttributes)

        // *** End programmer edit section *** (Speaker.Patronymic CustomAttributes)
        [StrLen(255)]
        public virtual string Patronymic
        {
            get
            {
                // *** Start programmer edit section *** (Speaker.Patronymic Get start)

                // *** End programmer edit section *** (Speaker.Patronymic Get start)
                string result = this.fPatronymic;
                // *** Start programmer edit section *** (Speaker.Patronymic Get end)

                // *** End programmer edit section *** (Speaker.Patronymic Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Speaker.Patronymic Set start)

                // *** End programmer edit section *** (Speaker.Patronymic Set start)
                this.fPatronymic = value;
                // *** Start programmer edit section *** (Speaker.Patronymic Set end)

                // *** End programmer edit section *** (Speaker.Patronymic Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SpeakerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerE", typeof(IIS.bookDemo.Speaker));
                }
            }
            
            /// <summary>
            /// "SpeakerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerL", typeof(IIS.bookDemo.Speaker));
                }
            }
        }
    }
}
